version: "3"
services:
   api:
     stdin_open: true
     tty: true
     build: .
     image: api.yourdomain
     container_name: api.yourdomain
     restart: always
     volumes:
       - /docker/deploy/your project:/deploy/app/your project
       - /docker/deploy/your project/logs:/deploy/app/your project/logs/
       - /docker/deploy/your project/gunicorn_log:/deploy/app/your project/gunicorn_log
     ports:
       - "5000:5000"
     command:
       - /bin/bash
       - -c
       - |
         cd /deploy/app
         gunicorn -c deploy/gunicorn.conf manage:app -D
         /bin/bash